# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Thunraz
email: thunraz@thunraz.com
description: >
  game dev, astronomy, photography 
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thunraz.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Julian'
bio: >
  I like to play games and sometimes I develop small games
  on my own or with friends of mine.
  I am also interested in astronomy and photography and the combination of the two.
author_image: "/assets/images/author.png"
twitter_username: thunraz
github_username:  thunraz
excerpt_separator:

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
